import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import TodoProvider from "@/context/TodoProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-slate-800">
      <body className={inter.className}>
        <Header />
        <TodoProvider>{children}</TodoProvider>
      </body>
    </html>
  );
}
